version: "3.7"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
  www:
    image: nasca/php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    links:
      - mysql:db
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:8080"
    links:
      - mysql:db
