version: "3.7"
services:
  www:
    image: nasca/php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - mysql:db
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.5.3.1-1
    ports:
      - "8080:8080"
    links:
      - mysql:db
    depends_on:
      - www
